name: feed_example
description: Example app using likemind's feed UI+SDK packages

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0

environment:
  sdk: '>=3.0.0 <=3.10.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  feed_sx:
    path: ../
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  connectivity_plus: ^3.0.4
  uni_links: ^0.5.1
  share_plus: ^6.3.2
  shared_preferences: ^2.1.0
  fluttertoast: 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true