name: feed_example
description: Example app using likemind's feed UI+SDK packages

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  feed_sx:
    path: ../
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  overlay_support: 2.1.0
  connectivity_plus: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true