name: feed_sx
description: Flutter sample UI package for LikeMinds Feed SDK
version: 1.4.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  chewie: ^1.4.0
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc:
  flutter_svg: ^1.1.6
  fluttericon: ^2.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path: ^1.8.2
  path_provider: ^2.0.14
  url_launcher: ^6.1.7
  video_player: ^2.6.1
  timeago: 
  image_picker: ^0.8.7+4
  collection: ^1.16.0
  lazy_load_scrollview: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  overlay_support: 2.1.0
  envied: ^0.3.0
  get_it: ^7.2.0
  photo_view: ^0.14.0
  extended_text_field: 12.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  file_picker: ^5.2.6
  open_filex: ^4.3.2
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0
  simple_s3: ^0.3.2
  shared_preferences: ^2.1.0
  uni_links: ^0.5.1
  share_plus: ^6.3.2
  visibility_detector: ^0.4.0+2
  flutter_typeahead: 
    path: lib/packages/flutter_typeahead-4.3.7
  multi_image_crop:
    path: lib/packages/multi_image_crop

  likeminds_feed: 1.3.0
  #  path: ../LikeMinds-Flutter-Feed-SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  

flutter:


  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/feed_sx/assets/icons/like.svg
    - packages/feed_sx/assets/icons/comment.svg
    - packages/feed_sx/assets/icons/bookmark.svg
    - packages/feed_sx/assets/icons/bookmark_filled.svg
    - packages/feed_sx/assets/icons/share.svg
    - packages/feed_sx/assets/icons/doc_pdf.svg
    - packages/feed_sx/assets/icons/cross.svg
    - packages/feed_sx/assets/icons/add_photo.svg
    - packages/feed_sx/assets/icons/add_video.svg
    - packages/feed_sx/assets/icons/add_attachment.svg
    - packages/feed_sx/assets/icons/reply.svg
    - packages/feed_sx/assets/icons/like_filled.svg
    - packages/feed_sx/assets/icons/posts.svg
    - packages/feed_sx/assets/icons/new_post.svg
    - packages/feed_sx/assets/icons/pin.svg
    - packages/feed_sx/assets/icons/gallery_plain.svg
    - packages/feed_sx/assets/icons/nothing.png
