name: Flutter Release on Master

# 1
on:
  # 2
  push:
  workflow_dispatch:
    branches:
      - master

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.3"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # 12
      #      - name: Run Flutter tests
      #        run: flutter test

      # Runs a set of commands using the runners shell
      # 13
      - name: Start Android release build
        run: |
          cd example/
          flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: example/build/app/outputs/apk/release/app-release.apk

      - name: Send APK to flutter-release channel
          uses: adrey/slack-file-upload-action@1.0.5
          with:
            token: ${{ secrets.SLACK_TOKEN }}
            path: .example/app/build/outputs/apk/debug/app-release.apk
            channel: random
            filename: Github Actions App.apk
            initial_comment: ${{ github.event.head_commit.message }}

      - name: Create Release tag
          uses: rickstaa/action-create-tag@v1
          id: "tag_create"
          with:
            tag: ${{ github.event.head_commit.message }}
            tag_exists_error: false
            message: ${{ github.event.head_commit.message }}
